version: '3.8'

services:
  app:
    image: my-777-app
    container_name: 777-app
    env_file:
      - set.env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
#    environment:
#      - SPRING_DATASOURCE_URL=${DB_URL}
#      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
#      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:13
#    environment:
#      POSTGRES_USER: ${DB_USERNAME}
#      POSTGRES_PASSWORD: ${DB_PASSWORD}
#      POSTGRES_DB: ${NAME_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local