telegram:
  api-url: ${TELEGRAM_API_URL:https://api.telegram.org/bot${telegram.bot-token}/sendMessage}
  bot-token: ${TELEGRAM_BOT_TOKEN:YOUR_TELEGRAM_BOT_TOKEN}
spring:
  application:
    name: reminder
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${NAME_DB:rdb}}
    username: ${DB_USERNAME:YOUR_DB_USERNAME}
    password:  ${DB_PASSWORD:YOUR_DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:liquibase/changelog.yml
  mail:
    host: smtp.mail.ru
    port: 465
    username: ${EMAIL_USER_NAME:YOUR_EMAIL_USER_NAME}
    password: ${EMAIL_PASSWORD:YOUR_EMAIL_PASSWORD}
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
            ssl:
              enable: true
            default-encoding: UTF-8
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:YOUR_GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET:YOUR_GOOGLE_CLIENT_SECRET}
            scope:
             - email
             - profile
          github:
            client-id: ${GITHUB_CLIENT_ID:YOUR_GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET:YOUR_GITHUB_CLIENT_SECRET}
            scope:
              - user
              - read:user
logging:
  file:
    name: app-logs
    path: /logs/
